process.on('uncaughtException', (err) ->
  console.log('now what?')
)